services:
  service:
    image: ${DOCKER_REGISTRY-}service
    build:
      context: .
      dockerfile: Service/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: redisUserAPI
    ports:
      - 6379:6379
volumes:
  pgdata: {}
